[features]
seeds = false
[programs.localnet]
token_swap = "Ds93hEKwNHR8MKkgJ7KApiEt6fQjdYJJD9vESo395XW4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/c98lab/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
