[features]
seeds = false
[programs.localnet]
token_swap = "Gc45jvXbsUf1f7rM1ZqfxaM3FD3owJJ6opnWssbwsKFu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/c98lab/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
